### ISSUE TITLE
Bring under the dev-tools umbrella

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rust-semverver#39]
Hey, we discussed making semverver a tool under the dev-tools team. I hope you think this is still a good idea! I can't remember exactly what we discussed as the next steps to do that. Here are a few things I can think of:

- [ ] get feedback from @killercup and @oli-obk (did you two get a chance to try this out?)
- [x] move to rust-lang-nursery
- [x] add a description and links to https://github.com/nrc/dev-tools-team/blob/master/overview.md

**Comment by oli-obk** [comment]
I tried it out on a bunch of crates of different sizes. While it has some kinks to be worked out, I think it is already useful as an initial decision helper for the version bump.

**Comment by ibabushkin** [comment]
Yes, I still believe this to be a good idea - to (hopefully) get more visible, which would speed up bug discovery and fixes a bit. When we decide to do this, I'll open a PR against the docs.

Other than that, I think the next reasonable step would be to discuss some of the bug-issues filed here, since I wasn't able to determine the exact cause for all of them yet.

**Comment by ibabushkin** [comment]
I'd like to bump this a bit. Any further comments on what needs to be done?

**Comment by nrc** [comment]
Once we move to the nursery, we also need to update some details on the dev-tools-team repo.

**Comment by ibabushkin** [comment]
@nrc I will file a PR for the dev-tools repo today.

**Comment by nrc** [comment]
Thanks!

**Comment by ibabushkin** [comment]
I *think* it's safe to close this now. Further feedback should get it's own issue. :)
